version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sign_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - ./dataset:/app/dataset
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    env_file:
      - ./.env

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sign_worker
    command: celery -A app.worker.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
      - ./dataset:/app/dataset
    depends_on:
      - redis
      - postgres
    env_file:
      - ./.env

  postgres:
    image: postgres:15
    container_name: sign_postgres
    environment:
      - POSTGRES_USER=signuser
      - POSTGRES_PASSWORD=signpass
      - POSTGRES_DB=signdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  redis:
    image: redis:6.2
    container_name: sign_redis
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sign_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    env_file:
      - ./.env

volumes:
  postgres_data:
